eureka:
  client:
    enabled: false

spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db
    username: sa
    password:
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      current_session_context_class: thread
      enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true