server:
  port: ${PORT:8002}

spring:
  profiles:
    active: dev
  application:
    name: social-service
  # DataBase
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    max-active: 50
    initial-size: 5
    max-idle: 10
    min-idle: 5
    test-while-idle: true
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000
    test-on-borrow: true
    validation-query: SELECT 1
    # Инициализация стартовых sql команд при запуске веб-приложения из отдельного файла
    # DataSource режимы инициализации: ALWAYS, EMBEDDED, NEVER
    initialization-mode: always

  # Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: thread
        enable_lazy_load_no_trans: true
    # Включает генерацию объектов (сущностей) в БД
    generate-ddl: true
    hibernate:
      # Позволяет более подробно управлять поведением генерации в БД
      ddl-auto: update
    show-sql: true
    # читабельный SQL
    format-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    # состояние статусов по умолчанию
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true